OrgDash/urls.py
from django.contrib import admin
from django.urls import path
from OrgDash import views

app_name = 'OrgDash'
urlpatterns = [

path('', views.OrganizerDashboard, name = 'organizer_dashboard'),


path('create/new/', views.SkateCreateView.as_view(), name = 'create_event'),
path('<int:pk>', views.EventDash, name = 'event_detail'),
path('<int:pk>/delete/', views.SkateDeleteView.as_view(), name = 'delete_event'),
path('<int:pk>/edit/', views.EventUpdateView.as_view(), name = 'event_update'),
path('<int:pk>/recurring', views.SkateRepeatUpdate.as_view(), name = 'skate_repeat_settings'),
path('<int:pk>/init/recurring', views.InitSkateRepeatUpdate.as_view(), name = 'init_skate_repeat_settings'),
path('<int:pk>/teams', views.TeamsView, name = 'make_teams'),
path('<int:pk>/send-message/', views.EmailGuests, name = 'email_guests'),
path('<int:pk>/message-all-invited/', views.EmailAllInvited, name = 'email_all_invited'),
path('<int:pk>/teams/finalize', views.FinalizeRosters, name = 'finalize_rosters'),



path('<int:pk>/invite/', views.CreateInvite.as_view(), name = 'create_invite'),
path('manage-invites/respond/<int:pk>', views.RespondToIinvite, name = 'update_invite'),
path('manage-invites/respond/confirm/<int:pk>/', views.InviteConfirm, name = 'invite_confirm_landing'),
path('<int:pk>/add-invites/', views.AddToInviteList, name='add_invites'),
path('finalize-invites/<int:pk>', views.FinalizeInvites, name = 'finalize_invites'),
path('<int:pk>/manage-invites/delete', views.DeleteInvite.as_view(), name = 'delete_invite'),



path('my-players/', views.PlayerDash, name='player_dash'),
path('my-players/create/', views.CreatePlayer.as_view(), name = 'create_player'),
path('my-players/<int:pk>', views.PlayerDetail.as_view(), name = 'player_detail'),
path('my-players/<int:pk>/edit/', views.PlayerUpdateView.as_view(), name = 'update_player'),
path('my-players/<int:pk>/delete/', views.PlayerDeleteView.as_view(), name = 'delete_player'),
path('my-players/upload-sheet', views.UploadSheet, name = 'upload_sheet'),


path('my-players/group/<int:pk>/delete', views.PlayerGroupDelete.as_view(), name = 'player_group_delete'),
path('my-players/new-group', views.Playergroups, name = 'create_player_group'),
path('my-players/group/<int:pk>/edit', views.UpdatePlayerGroup, name= 'player_group_update'),

]

pickupsports/urls.py
from django.contrib import admin
from django.urls import path, include
from pickuphockey import views
from quickteams.views import QuickTeams, CreateQuickPlayer
from django.contrib.auth import views as auth_views
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.homepage, name = 'home'),
    path('signup/', views.SignUp.as_view(), name = 'sign_up'),
    path("logout/", auth_views.LogoutView.as_view(), name= 'logout'),
    path("login/", views.CustomLogin.as_view(), name = 'login'),
    path("thanks/", views.Thanks, name = 'thanks'),
    path('contact/', views.Contact, name = 'contact'),
    path('message-sent', views.MessageSent, name = 'message_sent'),
    path('how-it-works', views.HowItWorks, name = 'how_it_works'),

    

    path('reset-password/', views.PasswordReset.as_view(), name ='reset_password'),
    path('reset-password-sent/', views.PasswordResetSent.as_view(), name ='password_reset_done'),
    path('reset/<uidb64>/<token>', views.PasswordResetFormView.as_view(), name ='password_reset_confirm'),
    path('reset-password-complete/', views.PasswordResetComplete.as_view(), name ='password_reset_complete'),
    path('organize/', include('OrgDash.urls')), 
    path('quick_teams/', include('quickteams.urls'))

]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__', include(debug_toolbar.urls))
    ] + urlpatterns

OrgDash/models.py
from django.db import models
from django.core.exceptions import ValidationError
import os
from django.contrib.auth.models import User
from django.utils import timezone
from datetime import timedelta
from django.core.mail import send_mail
from django.template.loader import render_to_string

from django.urls import reverse



class Player(models.Model):
    first_name = models.CharField(max_length=150, default= None)
    last_name = models.CharField(max_length=150, default= None)
    email = models.EmailField(max_length=150, default= None)
    skill = models.DecimalField(max_digits=4, decimal_places=1)
    created_by = models.ForeignKey(User, on_delete= models.CASCADE, default= 1)
    goalie = models.BooleanField(default= False, null= True)
   

    def get_absolute_url(self):
        return reverse('playerlist')

    def player_save(self):
        self.save()

    def __str__(self):
        return (self.first_name + " " + self.last_name)

    class Meta():
        unique_together= ("created_by", "email")



class Skate(models.Model):
    host = models.ForeignKey(User, on_delete= models.CASCADE, default= 1)
    date = models.DateField(auto_now = False, default= None)
    time = models.TimeField(auto_now=False, default= None)
    location = models.CharField(max_length=200)
    price = models.IntegerField()
    max_players = models.IntegerField(default=0)
    max_goalies = models.IntegerField(default=2)
    recurring_event = models.BooleanField(default= False)
    player_full = models.BooleanField(default=False)
    goalie_full = models.BooleanField(default=False)
    player_guests = models.ManyToManyField('Player', related_name= 'player_guests')
    goalie_guests = models.ManyToManyField('Player', related_name= 'goalie_guests')
    STATUS_CHOICES = [
        (7,'Every Week'),
        (14,'Every Two Weeks'),    
    ]
    frequency = models.IntegerField(choices=STATUS_CHOICES, default= 7, blank= True)
    send_invite_days_before = models.IntegerField(default= 3, blank= True)
    finalize_event_hours_before = models.IntegerField(default=1, blank= True)
    group_to_invite = models.ForeignKey('PlayerGroup', on_delete= models.CASCADE, blank= True, null=True)
    already_duplicated = models.BooleanField(default= False)
    auto_invites_sent = models.BooleanField(default=False)
    auto_rosters_sent = models.BooleanField(default= False)

    

    
    
    def get_next_skate_info(self):
        added_days = timedelta(days=int(self.frequency))
        
        next_event_date = self.date + added_days
      

        return {'host': self.host, 'date': next_event_date, 'time':self.time,'price': self.price, 'location': self.location,
                 'max_players': self.max_players, 'max_goalies' : self.max_goalies, 'recurring_event': self.recurring_event,'frequency': self.frequency,
                 'group_to_invite':self.group_to_invite,
                   'send_invite_days_before':self.send_invite_days_before, 'finalize_event_hours_before': self.finalize_event_hours_before}
  

    def __str__(self):
        return ("Event at " + self.location + " "  + str(self.date) + " " + str(self.time))




class Invitation(models.Model):
    host = models.ForeignKey(User, on_delete= models.CASCADE, default= 1)
    guest = models.ForeignKey(Player, on_delete=models.CASCADE)
    event = models.ForeignKey(Skate, on_delete=models.CASCADE)
    date_invited = models.DateTimeField(auto_now_add=True)
    STATUS_CHOICES = [
        ('Yes','Yes'),
        ('No','No'),
        ('Waitlist','Put me on the waitlist'),
    ]
    will_you_attend = models.CharField(max_length=256, choices=STATUS_CHOICES, default ='No')
    


    def update_event(self, waitlist_obj):
        if self.will_you_attend == 'Yes':
            if self.guest.goalie:
                self.event.goalie_guests.add(self.guest)
                waitlist_obj.guests.remove(self.guest)
            else:
                self.event.player_guests.add(self.guest)
                waitlist_obj.guests.remove(self.guest)
        elif self.will_you_attend == 'No':
            if self.guest.goalie:
                self.event.goalie_guests.remove(self.guest)
                waitlist_obj.guests.remove(self.guest)
            else:
                self.event.player_guests.remove(self.guest)
                waitlist_obj.guests.remove(self.guest)
        elif self.will_you_attend == 'Waitlist':
            waitlist_obj.guests.add(self.guest)
            waitlist_obj.save()
        self.event.save()
    
    def check_full(self):
        if len(self.event.player_guests.all()) == self.event.max_players:
            self.event.player_full = True
        else:
            self.event.player_full = False
        if len(self.event.goalie_guests.all()) == self.event.max_goalies:
            self.event.goalie_full = True
        else:
            self.event.goalie_full = False
        self.event.save()

    def __str__(self):
        if self.will_you_attend == 'Yes':
            return self.guest.first_name + " is going to "  + self.event.location 
        else:
            return self.guest.first_name +  " was invited to "  + self.event.location


    class Meta():
        unique_together= ("guest", "event")

class Waitlist(models.Model):
    event = models.ForeignKey(Skate, on_delete=models.CASCADE, blank= True)
    guests = models.ManyToManyField('Player')

   
    def __str__(self):
        return "Waitlist for " + self.event.location
    
    def notify_open_spot(self, inv_obj):
        for guest in self.guests.all():
                link = reverse('OrgDash:update_invite', kwargs={'pk': inv_obj.pk})
                subject = "A spot has opened up for " + str(self.event.host) + "'s event at " + self.event.location
                context = { 'event': self.event, 'guest':guest, 'link':link}
                if guest.goalie:
                    if self.event.goalie_full == False:
                        html_message = render_to_string('OrgDash/emails/spot_open_goalie.html', context)
                        send_mail(subject, 'message',self.event.host.email, [guest.email] , html_message=html_message)     
                else:
                    if self.event.player_full == False:
                        html_message = render_to_string('OrgDash/emails/spot_open_player.html', context)
                        send_mail(subject, 'message',self.event.host.email, [guest.email] , html_message=html_message)



class PlayerGroup(models.Model):
    created_by = models.ForeignKey(User, on_delete= models.CASCADE, default= 1)
    name = models.CharField(max_length=100, default= "Group Name")
    members = models.ManyToManyField('Player', related_name='groups')
    


    def __str__(self):
        return self.name + " group"


    
    
    
    
    
def validate_sheet_only(value):
    ext = os.path.splitext(value.name)[1]  
    valid_extensions = ['.xlsx', '.xlsm', '.xltx', '.xltm']  # define the valid extensions
    if not ext.lower() in valid_extensions:
        raise ValidationError('File type not supported. Only .xlsx, .xlsm, .xltx, .xltm files are allowed.')

class UploadSheet(models.Model):
    file = models.FileField(upload_to='OrgDash/uploads/', validators=[validate_sheet_only], default= None, null= True)

class InviteList(models.Model):
    event = models.ForeignKey(Skate, on_delete= models.CASCADE)
    guests = models.ManyToManyField('Player')
    message = models.TextField(max_length= 1500, default= "You're Invited!")

    def create_invites(self):
        guest_list = self.guests.all()
        existing_invites = Invitation.objects.filter(event=self.event)
        guests_already_invited =[invite.guest for invite in existing_invites]
        
        for guest in guest_list:
            if guest not in guests_already_invited:
                invite_data = {'host': self.event.host, 'guest': guest,'event': self.event}
                invite = Invitation(**invite_data)
                invite.save()
                

class LightTeam(models.Model):
    event = models.ForeignKey(Skate, on_delete= models.CASCADE, null=True)
    team = models.ManyToManyField('Player')
    skill = models.FloatField(default=0)
   

    def get_total_skill(self):
        light_team_members = self.team.all()
        skill_list = [member.skill for member in light_team_members]
        total_skill = sum(skill_list)
        self.skill = total_skill

class DarkTeam(models.Model):
    event = models.ForeignKey(Skate, on_delete= models.CASCADE, default=1, null= True)
    team = models.ManyToManyField('Player')
    skill = models.FloatField(default=0)
    

    def get_total_skill(self):
        light_team_members = self.team.all()
        skill_list = [member.skill for member in light_team_members]
        total_skill = sum(skill_list)
        self.skill = total_skill

class Bench(models.Model):
    event = models.ForeignKey(Skate, on_delete= models.CASCADE)
    bench_members = models.ManyToManyField('Player')


    def SetBench(self, guests, light_team_obj, dark_team_obj):
        light_team_ids = [player.pk for player in light_team_obj.team.all()]
        dark_team_ids = [player.pk for player in dark_team_obj.team.all()]
        bench = []
        for invite in guests:
            if invite.guest.pk not in light_team_ids:
                if invite.guest.pk not in dark_team_ids:
                    bench.append(invite.guest)
        self.bench_members.set(bench)
    

    

    

OrgDash/forms.py
from django import forms
from OrgDash.models import Skate, Invitation, Player, PlayerGroup, UploadSheet

from django.contrib.admin.widgets import FilteredSelectMultiple
from django.contrib.auth import get_user_model

class CreateEventForm(forms.ModelForm):
    
    def __init__(self, *args, **kwargs):
       super(CreateEventForm, self).__init__(*args, **kwargs)
       self.fields['host'].disabled = True
    
    class Meta:
        fields = (
            'host','date', 'time', 'location', 'price', 'max_players', 'max_goalies',
            'recurring_event',  )
        model = Skate

        widgets = {
        'host' : forms.Select(attrs={'class': 'form-control'}),
        'time' : forms.TimeInput(attrs={'type': 'time'}),
        'date' : forms.DateInput(attrs={'type': 'date'}),
        
        
        }
        

class UpdateEventForm(forms.ModelForm):
    class Meta:
        fields = (
            'date', 'time', 'location', 'price', 'max_players', 'recurring_event', 'max_goalies'
              )
        model = Skate

        widgets = {
        
        'time' : forms.TimeInput(attrs={'type': 'time'}),
        'date' : forms.DateInput(attrs={'type': 'date'}),
        }

class EventRepeatForm(forms.ModelForm):
    class Meta:
        fields = (
           'frequency', 'group_to_invite', 'send_invite_days_before', 'finalize_event_hours_before'
        )
        model = Skate
        widgets = {
        }

class InitEventRepeatForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
       super(InitEventRepeatForm, self).__init__(*args, **kwargs)
       self.fields['recurring_event'].disabled = True
    
    class Meta:
        fields = (
           'recurring_event','frequency', 'group_to_invite', 'send_invite_days_before', 'finalize_event_hours_before'
        )
        model = Skate
       



class CreateInviteForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
       super(CreateInviteForm, self).__init__(*args, **kwargs)
       self.fields['host'].disabled = True
       self.fields['event'].disabled = True
       

    class Meta:
        fields = ('host','event', 'guest', 'will_you_attend')
        model = Invitation

class InviteUpdateForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(InviteUpdateForm,self).__init__(*args, **kwargs)
        self.fields['guest'].disabled = True
        self.fields['will_you_attend'].choices = ('Yes', 'Yes'),('No','No')



    
    class Meta:
        fields = ('guest', 'will_you_attend')
        model = Invitation

class InviteWaitlistForm(forms.ModelForm):
    
    def __init__(self, *args, **kwargs):
        super(InviteWaitlistForm,self).__init__(*args, **kwargs)
        
        self.fields['guest'].disabled = True
        self.fields['will_you_attend'].choices = ('No','No'), ('Waitlist','Put me on the waitlist')
       
        

    class Meta:
        fields = ( 'guest', 'will_you_attend')
        model = Invitation

class CreatePlayerForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super(CreatePlayerForm, self).__init__(*args, **kwargs)
        self.fields['created_by'].disabled = True
        
    
    class Meta:
        fields = ('created_by', 'first_name','last_name', 'email', 'skill', 'goalie')
        model = Player

       

class PlayerUpdateForm(forms.ModelForm):
    class Meta:
        fields = ('first_name', 'last_name', 'email', 'skill', 'goalie')
        model = Player


class UploadSheetForm(forms.ModelForm):
    class Meta:
        fields= ('file',)
        model = UploadSheet


        
  
        
class UpdatePlayerGroupForm(forms.ModelForm):
    
    def __init__(self, *args, **kwargs):
       
        super(UpdatePlayerGroupForm, self).__init__(*args, **kwargs)
        self.fields['created_by'].disabled = True
        
        
    class Meta:
        fields = ('created_by', 'name','members')
        
        model = PlayerGroup
        widgets = {
             
            'members': forms.CheckboxSelectMultiple,
        }
        
        
# class CreateGoalieForm(forms.ModelForm):
#     def __init__(self, *args, **kwargs):
#         super(CreateGoalieForm, self).__init__(*args, **kwargs)
#         self.fields['created_by'].disabled = True
    
#     class Meta:
#         fields = ('created_by', 'player')
#         model = Goalie

OrgDash/templates/OrgDash/confirm_delete.html
{% extends 'base.html' %} 
{% block body_block %}


<div class="px-4 py-5 my-5 text-center">
    <form action="" method="post">
        {% csrf_token %} 
        <h1 class="display-5 fw-bold text-body-emphasis">Are you sure you want to delete {{object}}?</h1>
        <div class="col-lg-6 mx-auto">
        
        <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
            <input class="btn btn-danger btn-lg w-100" type="submit" value="Delete">
            <input type=button class="btn btn-gold btn-lg w-100" value="Cancel" onClick="javascript:history.go(-1);">
    </form>
      </div>
    </div>
  </div>




{% endblock %} 

OrgDash/templates/OrgDash/create_event.html
{% extends 'base.html' %} 
{% block body_block %}
{% load django_bootstrap5 %} 
<h1>Create New Event</h1>
<div class="container">
    <form action="" method="post">
        {% csrf_token %} 
        {% bootstrap_form form %}
<input type="submit" value="Create">
    </form>
<!-- <style>

    .hidden{
        display: none;
    }
</style> -->
<!-- <script>
    $("#id_recurring_event").on('click', function(){

$("#recurring").fadeToggle();

});




</script> -->












    {% endblock %} 

OrgDash/templates/OrgDash/event_detail.html
{% extends 'base.html' %} 
{% block body_block %}
<div class="container">
<h1>Event at {{event.location}} hosted by {{event.host}}</h1>
<h3>Date: {{event.date}}</h3>
<h3>Time: {{event.time}}</h3>
<br>
<h3>Price: ${{event.price}}</h3>
<br>
<br>
{% if event.recurring_event %}
<h2>This event repeats {{event.frequency}}</h2>

{% endif %} 
<h3>{{spots_left}} spots remaining. {{event.max_guests}} total spots</h3>
<h3>{{invites_sent}} guests have been invited</h3>
<br>



<form action="{% url 'OrgDash:event_update' event.pk %}">
    <button class="btn btn-warning">Edit</button>

    <br>
    <br>
    <br>
</form>

<form action="{% url 'OrgDash:delete_event' event.pk %}">
    <button class="btn btn-danger">Delete </button>
   

    <br>
    <br>
    <br>
</form>
<h1>Guest List</h1>
<br>
<form action="{% url 'OrgDash:send_invites' event.pk %}">
    <button class="btn btn-primary">Invite Multiple Players to this Event</button>
</form>
<br>

<form action="{% url 'OrgDash:invite_list' event.pk %}">
    <button class="btn btn-primary">Manage Invitations</button>
</form>
<br>

{% for guest in guest_list %}
<ul>
    <li>{{guest.guest}}</li>
</ul>
{% endfor %} 

<form action="{% url 'OrgDash:make_teams' event.pk %}">
    <button class="btn btn-primary">View Teams</button>
</form>
</div>
<br>
<br>
<br>
<div>
<form action="{% url 'OrgDash:create_invite' event.pk %}">
    <button class="btn btn-primary">Create Single Invite</button>
</form>




</div>

{% endblock %} 

OrgDash/templates/OrgDash/group_detail.html
{% extends 'base.html' %} 
{% block body_block %}
<div class="container">
    <h1>{{group.name}}</h1>
    <form action="{% url 'OrgDash:player_group_update' pk=group.pk %}">
        <button class="btn btn-warning">Edit Group</button>

      <br>
    </form>
    

    {% for player in members %}
    
    <ul>
    {{player.first_name}} {{player.last_name}}
    </ul>

</div>
{% endfor %} 
{% endblock %} 

OrgDash/templates/OrgDash/player_dash.html
{% extends 'base.html' %} 
{% block body_block %}

<div class="container">
    <h1>Players</h1>
    <div row="row">
        <form action="{% url 'OrgDash:create_player' %}">
         <button class="btn btn-primary">Create Player</button>

         <br>
         <br>
         <br>
     </form>
     <form action="{% url 'OrgDash:upload_sheet' %}">
        <button class="btn btn-primary">Create Players from Spreadsheet</button>

      <br>
    </form>
<br>
    <form action="{% url 'OrgDash:player_list' %}">
        <button class="btn btn-primary">View and Edit Players</button>

      <br>
    </form>
    <br>
    <br>
    <h2>Groups</h2>
    {% for group in my_groups %} 
    <ul>
        <a href="{% url 'OrgDash:player_group_detail' pk=group.pk %}">{{group.name}} </a>
        <form action="{% url 'OrgDash:player_group_delete' group.pk %}">
            <button class="btn btn-danger">Delete </button>
        </form>
     </ul>
     {% endfor %} 
    <form action="{% url 'OrgDash:create_player_group' %}">
      <button class="btn btn-primary">Create a Group of Players</button>

    <br>
  </form>

   
    {% if messages %}

    {% for message in messages %}
    
<script>


  const banner = document.createElement('div');
  banner.className = 'message_bannner'
  banner.textContent = '{{message}}';
  banner.style.backgroundColor = 'green';
  banner.style.color = 'white';
  banner.style.padding = '10px';
  banner.style.position = 'fixed';
  banner.style.top = '0';
  banner.style.left = '0';
  banner.style.width = '100%';
  banner.style.textAlign = 'center';
  banner.style.opacity = '1';
  banner.style.transition = 'opacity 2s'


  document.body.appendChild(banner);

  window.addEventListener('load', function() { //will not fade out
  setTimeout(function() {
    document.getElementsByClassName('message_bannner').style.opacity = '0';
  }, 2000); // 2000 milliseconds delay
});


</script>
    {% endfor %}

{% endif %}
{% endblock %} 

OrgDash/templates/OrgDash/player_detail.html
{% extends 'base.html' %} 
{% block body_block %}
<div class="container">
<h1>{{player.first_name}} {{player.last_name}}</h1>
<ul>
    <li>{{player.email}}</li>
    <li>{{player.skill}}</li>


</ul>



<form action="{% url 'OrgDash:update_player' object.pk %}">
    <button class="btn btn-warning">Edit</button>

    <br>
    <br>
    <br>
</form>

<form action="{% url 'OrgDash:delete_player' object.pk %}">
    <button class="btn btn-danger">Delete </button>
   

    <br>
    <br>
    <br>
</form>
<input type=button class="btn btn-secondary" value="Go Back" onClick="javascript:history.go(-1);">

{% endblock %} 

OrgDash/templates/OrgDash/player_list.html
{% extends 'base.html' %} 
{% block body_block %}
     {% for player in object_list %} 
     <ul>
        <a href="{{player.id}}">{{player.first_name}} {{player.last_name}} {{player.skill}} </a>
     </ul>
     {% endfor %} 


</div>

{% endblock %} 

OrgDash/templates/OrgDash/update.html
{% extends 'base.html' %} 
{% block body_block %}
{% load django_bootstrap5 %}

<div class="container">
    <div class="px-4 py-5 my-5 text-center">
        <h1 class="display-5 fw-bold text-body-emphasis">Edit {{object}}</h1>
        <div class="col-lg-6 mx-auto">
        </div>
      </div>
    <div class="col-md-6 create-form">
        <h2></h2>
        <form method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <div class="p-2">
            <input class=" w-100 btn btn-green btn-lg" type="submit" value="Update">
        </div>
        </form>
        <div class="p-2">
        <input type=button class="btn btn-gold btn-lg w-100" value="Cancel" onClick="javascript:history.go(-1);">
        </div>
    </div>
    
</div>
{% endblock %} 

OrgDash/templates/OrgDash/update_event.html
{% extends 'base.html' %} 
{% block body_block %}
{% load django_bootstrap5 %} 
<form method="post">
    {% csrf_token %}
    {% bootstrap_form form %}
    <input class="btn btn-secondary" type="submit" value="Update">
</form>


{% endblock %} 

OrgDash/templates/OrgDash/update_group.html
{% extends 'base.html' %} 
{% block body_block %}
<h1>{{current_group.name}}</h1>
<div class="container">
        <form method="POST" action="" >
            {% csrf_token %}
    <h2>Members</h2>
{% for member in members %}
<ul><input type="checkbox" id="{{member.pk}}" value="{{member.pk}}" name="members" checked>{{member}}</input></ul>
{% endfor %} 
<h2>Non members</h2>
{% for member in non_members %}
<ul><input type="checkbox" id="{{member.pk}}" value="{{member.pk}}" name="members" >{{member}}</input></ul>

{% endfor %} 

<button type="submit" >Update Group</button>

</div>
</form>
<br>
<input type=button class="btn btn-primary" value="Done" onClick="javascript:history.go(-1);">
{% endblock %} 