OrgDash/urls.py
from django.contrib import admin
from django.urls import path
from OrgDash import views

app_name = 'OrgDash'
urlpatterns = [

path('', views.OrganizerDashboard, name = 'organizer_dashboard'),


path('create/new/', views.SkateCreateView.as_view(), name = 'create_event'),
path('<int:pk>', views.EventDash, name = 'event_detail'),
path('<int:pk>/delete/', views.SkateDeleteView.as_view(), name = 'delete_event'),
path('<int:pk>/edit/', views.EventUpdateView.as_view(), name = 'event_update'),
path('<int:pk>/recurring', views.SkateRepeatUpdate.as_view(), name = 'skate_repeat_settings'),
path('<int:pk>/init/recurring', views.InitSkateRepeatUpdate.as_view(), name = 'init_skate_repeat_settings'),
path('<int:pk>/teams', views.TeamsView, name = 'make_teams'),
path('<int:pk>/send-message/', views.EmailGuests, name = 'email_guests'),
path('<int:pk>/message-all-invited/', views.EmailAllInvited, name = 'email_all_invited'),
path('<int:pk>/teams/finalize', views.FinalizeRosters, name = 'finalize_rosters'),



path('<int:pk>/invite/', views.CreateInvite.as_view(), name = 'create_invite'),
path('manage-invites/respond/<int:pk>', views.RespondToIinvite, name = 'update_invite'),
path('manage-invites/respond/confirm/<int:pk>/', views.InviteConfirm, name = 'invite_confirm_landing'),
path('<int:pk>/add-invites/', views.AddToInviteList, name='add_invites'),
path('finalize-invites/<int:pk>', views.FinalizeInvites, name = 'finalize_invites'),
path('<int:pk>/manage-invites/delete', views.DeleteInvite.as_view(), name = 'delete_invite'),



path('my-players/', views.PlayerDash, name='player_dash'),
path('my-players/create/', views.CreatePlayer.as_view(), name = 'create_player'),
path('my-players/<int:pk>', views.PlayerDetail.as_view(), name = 'player_detail'),
path('my-players/<int:pk>/edit/', views.PlayerUpdateView.as_view(), name = 'update_player'),
path('my-players/<int:pk>/delete/', views.PlayerDeleteView.as_view(), name = 'delete_player'),
path('my-players/upload-sheet', views.UploadSheet, name = 'upload_sheet'),


path('my-players/group/<int:pk>/delete', views.PlayerGroupDelete.as_view(), name = 'player_group_delete'),
path('my-players/new-group', views.Playergroups, name = 'create_player_group'),
path('my-players/group/<int:pk>/edit', views.UpdatePlayerGroup, name= 'player_group_update'),

]

pickupsports/urls.py
from django.contrib import admin
from django.urls import path, include
from pickuphockey import views
from quickteams.views import QuickTeams, CreateQuickPlayer
from django.contrib.auth import views as auth_views
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.homepage, name = 'home'),
    path('signup/', views.SignUp.as_view(), name = 'sign_up'),
    path("logout/", auth_views.LogoutView.as_view(), name= 'logout'),
    path("login/", views.CustomLogin.as_view(), name = 'login'),
    path("thanks/", views.Thanks, name = 'thanks'),
    path('contact/', views.Contact, name = 'contact'),
    path('message-sent', views.MessageSent, name = 'message_sent'),
    path('how-it-works', views.HowItWorks, name = 'how_it_works'),

    

    path('reset-password/', views.PasswordReset.as_view(), name ='reset_password'),
    path('reset-password-sent/', views.PasswordResetSent.as_view(), name ='password_reset_done'),
    path('reset/<uidb64>/<token>', views.PasswordResetFormView.as_view(), name ='password_reset_confirm'),
    path('reset-password-complete/', views.PasswordResetComplete.as_view(), name ='password_reset_complete'),
    path('organize/', include('OrgDash.urls')), 
    path('quick_teams/', include('quickteams.urls'))

]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__', include(debug_toolbar.urls))
    ] + urlpatterns

quickteams/urls.py
from django.contrib import admin
from django.urls import path
from quickteams import views

app_name = 'quickteams'
urlpatterns = [

path('', views.QuickTeams, name='quick_teams'),
path('create-player', views.CreatePlayer.as_view(), name = 'create_quick_player'),
path('edit-player/<int:pk>', views.EditQuickPlayer.as_view(), name = 'update_quick__player'),
path('delete-player/<int:pk>', views.DeleteQuickPlayer.as_view(), name = 'delete_quick_player'),

]

pickuphockey/models.py
from django.conf import settings
from django.db import models



class EmailVerification(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        on_delete=models.CASCADE,
        related_query_name="verification"
    )
    verified = models.BooleanField(default=False)

    
    














   

pickuphockey/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm, PasswordResetForm
from django.contrib.auth.models import User
from django.contrib.auth import get_user_model


# User = get_user_model()

class SignUp(UserCreationForm, forms.Form):
    class Meta:
        fields = ( 'username', 'email','password1', 'password2',)
        model = User

class LoginForm(AuthenticationForm):
    username = forms.EmailField(label="Email", widget=forms.EmailInput(attrs={'autofocus': True, 'class': 'form-control'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'form-control'}))
  



class CustomPasswordResetForm(PasswordResetForm):
    def clean_email(self):
        email = self.cleaned_data['email']
        UserModel = get_user_model()
        if not UserModel.objects.filter(email__iexact=email, is_active=True).exists():
            raise forms.ValidationError(("There is no user registered with the specified email address!"))
        return email











    


            

pickuphockey/views.py
from django.shortcuts import render, redirect
from django.views.generic import CreateView
from pickuphockey.forms import SignUp, LoginForm, CustomPasswordResetForm
from django.urls import reverse_lazy
from django.contrib.auth.views import LoginView, PasswordResetView, PasswordResetConfirmView, PasswordResetDoneView, PasswordResetCompleteView
from django.contrib.auth import login
from django.core.mail import send_mail





def baseview(request):
    return render(request, 'base.html')

def homepage(request):
    return render(request, 'home.html')




class SignUp(CreateView):
    form_class = SignUp
    success_url = reverse_lazy('home')
    template_name = 'sign_up.html'

    def form_valid(self, form):
        request = super().form_valid(form)
        user = form.save()
        login(self.request, user)
        return request 
    
class CustomLogin(LoginView):
    form_class = LoginForm
    template_name = 'registration/login.html'
    success_url = reverse_lazy('OrgDash:player_dash')
    



class PasswordReset(PasswordResetView):
    template_name = 'registration/reset_password.html'
    form_class = CustomPasswordResetForm
    

class PasswordResetSent(PasswordResetDoneView):
    template_name = 'registration/password_reset_sent.html'
   

class PasswordResetFormView(PasswordResetConfirmView):
    template_name = 'registration/password_reset_form.html'

class PasswordResetComplete(PasswordResetCompleteView):
    template_name = 'registration/password_reset_done.html'

def Thanks(request):
    return render(request, 'thanks.html')

def MessageSent(request):
    return render(request, 'message_sent.html')

def Contact(request):
    if request.method == 'POST':
        from_email = request.POST.get('inputemail')
        message = request.POST.get('message')
        name = request.POST.get('name')
        confirm_message = "<h1>Thank you for reaching out</h1><br><p>We are currently reviewing your message and will respond as soon as we can</p><br><h2>Your message:</h2><br> " + message
        inbound_message = "<h1>Message from " + name + "<h1><br><h2>Email: " + from_email + "<br><h2>Message: " + message
        # email to site
        send_mail("Contact form recieved from " + name, 'message' , from_email,  ['pickuphockey1@gmail.com'], html_message=inbound_message)
        # email copy for sender
        send_mail("Hi " + name +" thanks for your message,", 'message', 'pickuphockey1@gmail.com' ,  [from_email], html_message=confirm_message)
       
        return redirect('message_sent')
    else:
        return render(request, 'contact.html')
    
def HowItWorks(request):
    return render(request, 'how_it_works.html')




   

pickuphockey/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://unpkg.com/@popperjs/core@2"></script>
    <script src="https://code.jquery.com/jquery-3.6.3.js" integrity="sha256-nQLuAZGRRcILA+6dMBOvcRh5Pe310sBpanc6+QBmyVM=" crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" crossorigin="anonymous"></script>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Barlow:wght@200;300;400;500;600;700;800&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'pickuphockey.css' %}">
    <title>PickUpPuck.com</title>
    <link rel="icon" type="image/x-icon" href="{% static 'photos/hockey-helmet-1-svgrepo-com.png' %}">
</head>



<nav class="navbar navbar-expand-lg main-nav py-3" aria-label="Ninth navbar example">
  <div class="container-xl">
    <a href="/" class="navbar-brand brand-link "><img src="{% static 'photos/Logo4brand.png' %}" class="img-fluid" alt=""></a>
    <button class="navbar-toggler" type="button" style="background-color: #FF9E1F;" data-bs-toggle="collapse" data-bs-target="#navbarsExample07XL" aria-controls="navbarsExample07XL" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    {% if user.is_authenticated %}
    <div class="collapse navbar-collapse" id="navbarsExample07XL">
      
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        
        <li class="nav-item dropdown px-2">
          <a class="nav-link dropdown-toggle active nav-links" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
           Events
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'OrgDash:organizer_dashboard' %}">View My Events</a></li>
            <li>
              <hr class="dropdown-divider">
            </li>
            <li><a class="dropdown-item" href="{% url 'OrgDash:create_event' %}">Create New Event</a></li>
            
          </ul>
        </li>
        <li class="nav-item dropdown px-2">
          <a class="nav-link dropdown-toggle active nav-links" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            My Players
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="{% url 'OrgDash:player_dash' %}">Manage My Players</a></li>
            
            <li>
              <hr class="dropdown-divider">
            </li>
            <li><a class="dropdown-item" href="{% url 'OrgDash:create_player' %}">Create Player</a></li>
            
          </ul>
        </li>
        <li class="px-2"><a href="{% url 'contact' %}" class="nav-links nav-link link-body-emphasis">Contact</a></li>
        
        <li class="px-2"><a href="{% url 'how_it_works' %}" class="nav-links nav-link link-body-emphasis">How it Works</a></li>
        <li class="px-2"><a href="{% url 'quickteams:quick_teams' %}" class="nav-links nav-link link-body-emphasis">Quick Teams</a></li>

        <li class="nav-item dropdown px-2 ">
          <a class="nav-link dropdown-toggle active nav-links" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Hello {{user}}
          </a>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item" href="/logout/">Log Out</a></li>
            
            <li>
              <hr class="dropdown-divider">
            </li>
            <a class="dropdown-item" href="/reset-password/">Reset Password</a></li>
            
          </ul>
        </li>
      </ul>
      
    </div>
    {% else %}
    <div class="collapse navbar-collapse" id="navbarsExample07XL">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      <li class="px-2"><a href="{% url 'contact' %}" class="nav-links nav-link link-body-emphasis px-5">Contact</a></li>
      
      <li><a href="{% url 'how_it_works' %}" class="nav-links nav-link link-body-emphasis px-5">How it Works</a></li>
    </ul>
      <div class="col-md-3 text-end px-2">
        <a type="button" href="{% url 'sign_up' %}" class="btn btn-green">Sign Up</a>
        <a type="button" href="{% url 'login' %}" class="btn btn-gold">Log In</a>
      </div>
      
    </div>
    </div>
    </nav>
      {% endif %} 
  </div>
</nav>

   
    <body>
    
    
                {% block body_block%} 
                {% endblock %} 
     


   
    


    
</body>
</html>

pickuphockey/templates/contact.html
{% extends 'base.html' %} 
{% block body_block %}
<div class="container p-2">
    <div class="d-flex justify-content-center">
        <div class="col-md-8">
            <div class="py-5">
                <h1 class="py-3">Contact Us</h1>
                <p>Please share any questions, comments or concerns about our site. For assistance using our event hosting application, 
                    visit our <a href="{% url 'how_it_works' %}">How it Works </a> page.</p>
            </div>
        <form class="row g-3" method="post">
        {% csrf_token %}
        <label for="name" class="form-label">Name</label>
        <input type="text" class="form-control" id="name" name = "name">
    
        <label for="inputemail" class="form-label">Email</label>
        <input type="email" class="form-control" id="inputemail" name = "inputemail">
        <label for="message" class="form-label">Message</label>
            <textarea class="form-control" placeholder="Your message here" id="message" name="message" style="height: 300px"></textarea>
        <div class="col-8 mx-auto">
        <button type="submit" class=" w-100 btn btn-green btn-lg">Send</button>
        </div>
    </form>
    </div>
</div>
<script src="https://cdn.tiny.cloud/1/s238kxbjuhmteauqdtczt0r4hlpafcw6lr6lytndfv7jvz0j/tinymce/6/tinymce.min.js" referrerpolicy="origin"></script>
<script>
    tinymce.init({
      selector: 'textarea',
    
      // plugins: 'anchor autolink charmap codesample emoticons image link lists media searchreplace table visualblocks wordcount checklist mediaembed casechange export formatpainter pageembed linkchecker a11ychecker tinymcespellchecker permanentpen powerpaste advtable advcode editimage tinycomments tableofcontents footnotes mergetags autocorrect typography inlinecss template importcss',
      toolbar: 'undo redo | blocks fontfamily fontsize | bold italic underline strikethrough | link image media table mergetags | addcomment showcomments | spellcheckdialog a11ycheck typography | align lineheight | checklist numlist bullist indent outdent | emoticons charmap | removeformat',
      extended_valid_elements: 'span[class]',
      tinycomments_mode: 'embedded',
      tinycomments_author: 'Author name',
      mergetags_list: [
        { value: 'First.Name', title: 'First Name' },
        { value: 'Email', title: 'Email' },
      ],
    });
  </script>
  {% endblock %} 

pickuphockey/templates/create_profile.html
{% extends 'base.html' %} 
{% block body_block %}
{% load django_bootstrap5 %} 
<h1>Hello {{user.username}}</h1>
<H2>Answer the following questions</H2>
<div class="container">
    <form action="" method="post">
        {% csrf_token %} 
        {% bootstrap_form form %}
<input type="submit" value="Sign Up">
    </form>

</div>
{% endblock %} 

pickuphockey/templates/home.html
{% extends 'base.html' %} 
{% block body_block %}
{% load static %} 

<main>
    <div class="text-center p-4">
      
       
        <div class=" p-5 text-center">
          <img src="{% static 'photos/Logo4crop.PNG' %}" alt="" class="img-fluid">
           
        </div>
          
         
          
            <br>
            <br>
            <div class="container my-5">
              <div class="row p-4 grid gap-0 column-gap-5 rounded-3 border shadow-lg">
                <div class="col-lg-7 py-2 px-4 ">
                  <h1 class="display-4 fw-bold lh-1 text-body-emphasis">An all in one event manager for hockey</h1>
                  <p class="lead px-2 py-4">Set up events, invite guests and make teams for the day of the event. </p>
                  {% if user.is_authenticated %}
                  <div class="d-grid gap-3 d-md-flex justify-content-md-start mb-4 mb-lg-3">
                    <a type="button" href="{% url 'OrgDash:player_dash' %}" class=" btn btn-lg btn-blue w-100">My Player Dashboard</a>
                  </div>
                  {% endif %} 
                </div>
                <div class="col-lg-4 p-2">
                    <img class="img-fluid" src="{% static 'photos/equip.jpg' %}" alt="" width="">
                    <small><a href="https://www.freepik.com/free-vector/hockey-icons-set_2871279.htm#query=hockey%20arena&position=21&from_view=keyword&track=ais">Image by macrovector</a> on Freepik</small>
                </div>
              </div>
            </div>
            <div class="b-example-divider"></div>
            <div class="container my-5">
              <div class="row p-4 grid gap-0 column-gap-5 rounded-3 border shadow-lg">
                <div class="col-lg-4 p-2">
                  <img class="img-fluid" src="{% static 'photos/comp.jpg' %}" alt="" width="">
                  <small><a href="https://www.freepik.com/free-vector/hockey-icons-set_2871279.htm#query=hockey%20arena&position=21&from_view=keyword&track=ais">Image by macrovector</a> on Freepik</small>
              </div>
                <div class="col-lg-7 py-2 px-4 ">
                  <h1 class="display-4 fw-bold lh-1 text-body-emphasis">It's all Automatic</h1>
                  <p class="lead px-2 py-4">Set your events to auto repeat and let us handle the rest. You can provide a personal touch as much or as little as you would like.</p>
                  {% if user.is_authenticated %}
                  <div class="d-grid gap-2 d-md-flex justify-content-md-start mb-4 mb-lg-3">
                    <a type="button" href="{% url 'OrgDash:organizer_dashboard' %}" class="btn btn-lg btn-green w-100">My Event Dashboard</a>
                  </div>
                  {% endif %} 
                </div>
                
              </div>
            </div>
        <div class="container marketing p-4">
    
        
          <div class="container my-5">
            <div class="row p-4 grid gap-0 column-gap-5 rounded-3 border shadow-lg">
              <div class="col-lg-7 py-2 px-4 ">
                <h1 class="display-4 fw-bold lh-1 text-body-emphasis">Make teams with ease</h1>
                <p class="lead px-2 py-4">Sort players by their skill to make the most even teams possible</p>
                {% if user.is_authenticated %} 
                <div class="d-grid gap-2 d-md-flex justify-content-md-start mb-4 mb-lg-3">
                  <a type="button" href="{% url 'quickteams:quick_teams' %}" class="btn btn-lg btn-gold w-100">Make Quick Teams</a>
                </div>
                {% endif %} 
              </div>
              <div class="col-lg-4 p-2">
                  <img class="img-fluid" src="{% static 'photos/goalie1.jpg' %}" alt="" width="">
                  <small><a href="https://www.freepik.com/free-vector/hockey-icons-set_2871279.htm#query=hockey%20arena&position=21&from_view=keyword&track=ais">Image by macrovector</a> on Freepik</small>
              </div>
            </div>
          </div>
    
        <hr class="featurette-divider">
    
        <div class="bg-dark text-secondary px-4 py-5 text-center">
          <div class="py-5">
            <h1 class="display-5 fw-bold text-white">How does it work?</h1>
            <div class="col-lg-6 mx-auto"> 
              <div class="d-grid gap-2 d-sm-flex justify-content-sm-center">
                <a type="button" href="{% url 'how_it_works' %}" class="btn btn-outline-info btn-lg px-4 me-sm-3 fw-bold">Check out the how to guide</a>
               
              </div>
            </div>
          </div>
        </div>
        
    
    
    
        <!-- /END THE FEATURETTES -->
    
        </div><!-- /.container -->
    
    
       
    </div>
  </main>

  {% endblock %} 

pickuphockey/templates/sign_up.html
{% extends 'base.html' %} 
{% load django_bootstrap5 %} 
{% block body_block %}
<div class="container">
    <div class="d-flex justify-content-center p-5">
        <div class="col-md-6">
        <h1>Sign up</h1>

        <form action="" method="post">
            {% csrf_token %} 
            {% bootstrap_form form %}
        
            <input type="submit" class="btn btn-green btn-lg w-100" value="Sign Up">
            <br>
            <div class="py-4 px-2 text-center">
                <a class="" href="{% url 'login' %}">Already have an account? Click here to log in</a>
            </div>
        </form>

       
    </div>
    </div>
</div>
{% endblock %} 

pickuphockey/templates/sign_up_host.html
{% extends 'base.html' %} 
{% block body_block %}
<H1> Sign up as a host</H1>
<div class="container">
    <form action="" method="post">
        {% csrf_token %} 
        {% bootstrap_form form %}
<input type="submit" value="Sign Up">
    </form>

</div>
{% endblock %} 

pickuphockey/templates/sign_up_player.html
{% extends 'base.html' %} 
{% load django_bootstrap5 %} 
{% block body_block %}

<h1> Sign up as a guest</h1>
<div class="container">
    <form action="" method="post">
        {% csrf_token %} 
        {% bootstrap_form form %}
<input type="submit" value="Sign Up">
    </form>

</div>
{% endblock %} 

pickuphockey/templates/thanks.html
{% extends 'base.html' %} 
{% block body_block %}


<div class="container-fluid py-5">
    <h1 class="display-5 fw-bold">You have been logged out</h1>
    <p class="col-md-8 fs-4">Thank you for using our site today</p>
    <a type="button" class="btn btn-blue" href="{% url 'login' %}">Log in again</a>
    <a type="button" class="btn btn-gold" href="{% url 'home' %}">Back to home</a>
  </div>












{% endblock %} 