OrgDash/urls.py
from django.contrib import admin
from django.urls import path
from OrgDash import views

app_name = 'OrgDash'
urlpatterns = [

path('', views.OrganizerDashboard, name = 'organizer_dashboard'),


path('create/new/', views.SkateCreateView.as_view(), name = 'create_event'),
path('<int:pk>', views.EventDash, name = 'event_detail'),
path('<int:pk>/delete/', views.SkateDeleteView.as_view(), name = 'delete_event'),
path('<int:pk>/edit/', views.EventUpdateView.as_view(), name = 'event_update'),
path('<int:pk>/recurring', views.SkateRepeatUpdate.as_view(), name = 'skate_repeat_settings'),
path('<int:pk>/init/recurring', views.InitSkateRepeatUpdate.as_view(), name = 'init_skate_repeat_settings'),
path('<int:pk>/teams', views.TeamsView, name = 'make_teams'),
path('<int:pk>/send-message/', views.EmailGuests, name = 'email_guests'),
path('<int:pk>/message-all-invited/', views.EmailAllInvited, name = 'email_all_invited'),
path('<int:pk>/teams/finalize', views.FinalizeRosters, name = 'finalize_rosters'),



path('<int:pk>/invite/', views.CreateInvite.as_view(), name = 'create_invite'),
path('manage-invites/respond/<int:pk>', views.RespondToIinvite, name = 'update_invite'),
path('manage-invites/respond/confirm/<int:pk>/', views.InviteConfirm, name = 'invite_confirm_landing'),
path('<int:pk>/add-invites/', views.AddToInviteList, name='add_invites'),
path('finalize-invites/<int:pk>', views.FinalizeInvites, name = 'finalize_invites'),
path('<int:pk>/manage-invites/delete', views.DeleteInvite.as_view(), name = 'delete_invite'),



path('my-players/', views.PlayerDash, name='player_dash'),
path('my-players/create/', views.CreatePlayer.as_view(), name = 'create_player'),
path('my-players/<int:pk>', views.PlayerDetail.as_view(), name = 'player_detail'),
path('my-players/<int:pk>/edit/', views.PlayerUpdateView.as_view(), name = 'update_player'),
path('my-players/<int:pk>/delete/', views.PlayerDeleteView.as_view(), name = 'delete_player'),
path('my-players/upload-sheet', views.UploadSheet, name = 'upload_sheet'),


path('my-players/group/<int:pk>/delete', views.PlayerGroupDelete.as_view(), name = 'player_group_delete'),
path('my-players/new-group', views.Playergroups, name = 'create_player_group'),
path('my-players/group/<int:pk>/edit', views.UpdatePlayerGroup, name= 'player_group_update'),

]

pickupsports/urls.py
from django.contrib import admin
from django.urls import path, include
from pickuphockey import views
from quickteams.views import QuickTeams, CreateQuickPlayer
from django.contrib.auth import views as auth_views
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.homepage, name = 'home'),
    path('signup/', views.SignUp.as_view(), name = 'sign_up'),
    path("logout/", auth_views.LogoutView.as_view(), name= 'logout'),
    path("login/", views.CustomLogin.as_view(), name = 'login'),
    path("thanks/", views.Thanks, name = 'thanks'),
    path('contact/', views.Contact, name = 'contact'),
    path('message-sent', views.MessageSent, name = 'message_sent'),
    path('how-it-works', views.HowItWorks, name = 'how_it_works'),

    

    path('reset-password/', views.PasswordReset.as_view(), name ='reset_password'),
    path('reset-password-sent/', views.PasswordResetSent.as_view(), name ='password_reset_done'),
    path('reset/<uidb64>/<token>', views.PasswordResetFormView.as_view(), name ='password_reset_confirm'),
    path('reset-password-complete/', views.PasswordResetComplete.as_view(), name ='password_reset_complete'),
    path('organize/', include('OrgDash.urls')), 
    path('quick_teams/', include('quickteams.urls'))

]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__', include(debug_toolbar.urls))
    ] + urlpatterns

OrgDash/views.py
from django.shortcuts import render, redirect
from OrgDash.models import Skate, Invitation, Player, PlayerGroup, InviteList, Waitlist, LightTeam, DarkTeam, Bench
from django.contrib import messages
from django.views.generic import CreateView, DetailView, DeleteView, UpdateView, ListView
from OrgDash.forms import (CreateEventForm, UpdateEventForm, CreateInviteForm, CreatePlayerForm,
PlayerUpdateForm, InviteUpdateForm, InviteWaitlistForm,EventRepeatForm, InitEventRepeatForm, UploadSheetForm, 
)
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
from django.core.mail import send_mail
from django.template.loader import render_to_string
from django.db.models import Q
from django.urls import reverse_lazy, reverse
from django.utils import timezone










@login_required
def OrganizerDashboard(request):
    today=timezone.now()
    active_user = request.user.pk
    todays_events = Skate.objects.filter(Q(host= active_user) & Q(date=today))
    upcoming_events = Skate.objects.filter(Q(host= active_user) & Q(date__gt= today))
    past_events = Skate.objects.filter(Q(host= active_user) & Q(date__lt= today))
    context = {'upcoming_events' : upcoming_events, 'past_events': past_events, 'todays_events': todays_events}
    return render (request,'OrgDash/dash_base.html',context)
   

##################SKATES/EVENTS##########################

class SkateCreateView(LoginRequiredMixin, CreateView):
    template_name = 'OrgDash/Skates/create_event.html'
    success_url = reverse_lazy('OrgDash:organizer_dashboard')
    form_class= CreateEventForm
    model = Skate

    def get_initial(self):
        return {'host': self.request.user}
    
    def get_success_url(self):
            if self.object.recurring_event == True:
                return reverse_lazy('OrgDash:skate_repeat_settings', args=[self.object.pk])
            else:
                return super().get_success_url()
            
   


class SkateRepeatUpdate(LoginRequiredMixin, UpdateView):
    model = Skate
    template_name = 'OrgDash/Skates/skate_repeat_form.html'
    form_class = EventRepeatForm

    def get_success_url(self):
        return reverse('OrgDash:event_detail', args=[self.object.pk])
    
    def get_form_class(self):
        modelform = super().get_form_class()
        modelform.base_fields['group_to_invite'].limit_choices_to = {'created_by': self.request.user}
        return modelform
    

class InitSkateRepeatUpdate(LoginRequiredMixin, UpdateView):
    model = Skate
    template_name = 'OrgDash/Skates/skate_repeat_form.html'
    form_class = InitEventRepeatForm

    def get_success_url(self):
        return reverse('OrgDash:event_detail', args=[self.object.pk])
    
    def get_form_class(self):
        modelform = super().get_form_class()
        modelform.base_fields['group_to_invite'].limit_choices_to = {'created_by': self.request.user}
        return modelform
    
    def get_initial(self):
        return {'recurring_event': True} 

    
class SkateDeleteView(LoginRequiredMixin, DeleteView): 
    model = Skate
    template_name = 'OrgDash/confirm_delete.html'
    success_url = reverse_lazy('OrgDash:organizer_dashboard')

    
class EventUpdateView(LoginRequiredMixin, UpdateView):
    model = Skate
    form_class = UpdateEventForm
    template_name = 'OrgDash/update.html'
    
    def get_success_url(self):
        return reverse('OrgDash:event_detail', args=[self.object.pk])

@login_required
def TeamsView(request, pk):
    from OrgDash.team_sort import SortTeams, SetTeams, RemoveFromTeam, AddToTeam
    active_user = request.user.pk
    active_event = Skate.objects.get(pk=pk)
    guests = Invitation.objects.filter(Q(host= active_user) & Q(event= active_event) & Q(will_you_attend= 'Yes'))
    skaters = active_event.player_guests.all()
    goalies = active_event.goalie_guests.all()
    
   
    #Take player skill and make teams
    player_data =[((guest), float(guest.skill)) for guest in skaters]
    goalie_data = [((guest), float(guest.skill)) for guest in goalies]
    
    # #set light team
    light_team_tup = LightTeam.objects.get_or_create(event=active_event)
    light_team_obj = light_team_tup[0]
    light_team_obj.get_total_skill()
    
    # set dark team
    dark_team_tup = DarkTeam.objects.get_or_create(event=active_event)
    dark_team_obj = dark_team_tup[0]
    dark_team_obj.get_total_skill()
    
    # set bench
    bench_obj = Bench.objects.get_or_create(event=active_event)
    bench_obj[0].SetBench(guests, light_team_obj, dark_team_obj)
   
    total_skill = (float(dark_team_obj.skill) + float(light_team_obj.skill))
    context = {'light_team': light_team_obj.team.all(), 'dark_team': dark_team_obj.team.all(), 'total_skill':total_skill, 'active_event':active_event,
                'light_team_skill' : light_team_obj.skill, 'dark_team_skill': dark_team_obj.skill, 'bench_members': bench_obj[0].bench_members.all()}
    
    
    if request.method == 'POST':
        sort_action = request.POST.get('auto_sort')
        light_form_action = request.POST.get('light_form_action')
        dark_form_action = request.POST.get('dark_form_action')
        bench_action = request.POST.get('bench_action')
        
        if sort_action == 'auto_sort':
            teams = SortTeams(player_data, goalie_data)
            SetTeams(teams, active_event)
            
          
        if light_form_action == 'remove_player_light':
            selected_player_ids = request.POST.getlist('light_player')
            RemoveFromTeam(light_team_obj, selected_player_ids)
            
        if dark_form_action == 'remove_player_dark':
            selected_player_ids = request.POST.getlist('dark_player')
            RemoveFromTeam(dark_team_obj, selected_player_ids)
            
        if bench_action == 'add_to_light':
            selected_player_ids = request.POST.getlist('bench_player')
            AddToTeam(light_team_obj, selected_player_ids)
            
        elif bench_action == 'add_to_dark':
            selected_player_ids = request.POST.getlist('bench_player')
            AddToTeam(dark_team_obj, selected_player_ids)

        return redirect(reverse('OrgDash:make_teams', args=[active_event.pk]), context)
    else:
    
        return render (request,'OrgDash/Skates/make_teams2.html',context)


@login_required
def EventDash(request, pk): 
    active_user = request.user.pk
    active_event = Skate.objects.get(pk=pk)
    my_player_groups = PlayerGroup.objects.filter(created_by = active_user).all()
    invite_list_obj, created = InviteList.objects.get_or_create(event= active_event)
    if created == False:
        invite_list_obj.guests.clear()
    
    all_invited = Invitation.objects.filter(Q(host= active_user) & Q(event=active_event))
    
    player_list = active_event.player_guests.all()
    goalie_list = active_event.goalie_guests.all()
    wait_list_obj, created = Waitlist.objects.get_or_create(event=active_event)
    wait_list = wait_list_obj.guests.all()
    spots_left = active_event.max_players - len(active_event.player_guests.all())
    goalie_spots_left = active_event.max_goalies - len(active_event.goalie_guests.all())
    
    
    
    context = {'event': active_event, 'guest_list': player_list, 'goalie_list':goalie_list, 'guest_num':(len(player_list) + len(goalie_list)), 
               'spots_left': spots_left, 'goalie_spots_left': goalie_spots_left, 'player_groups':my_player_groups,
                  'wait_list':wait_list, 'wait_num':len(wait_list), 'all_invited': all_invited }
    if request.method == "POST":
        group_id = request.POST.get('invite_group')
        selected_group_members = PlayerGroup.objects.get(id=group_id).members.all()
        for member in selected_group_members:
            invite_list_obj.guests.add(member)
    
        return redirect(reverse('OrgDash:finalize_invites' ,args=[active_event.pk]), context)
    else:
        return render(request, 'OrgDash/Skates/event_detail2.html', context)



@login_required
def FinalizeRosters(request, pk):
    current_event = Skate.objects.get(pk=pk)
    dark_team = DarkTeam.objects.get(event=current_event)
    light_team = LightTeam.objects.get(event=current_event)
    dark_team_members = dark_team.team.all()
    light_team_members = light_team.team.all()
    
    player_emails = [player.email for player in light_team_members] +[player.email for player in dark_team_members]
    
   
    event_host = current_event.host
    context= {'light_team_members': light_team_members, 'dark_team_members':dark_team_members, 'event':current_event}
    if request.method == 'POST':
        message_field = request.POST['tinymce_email_invite']
        
        
        
        subject = "Rosters for" + event_host.first_name + "'s event at " + current_event.location
        message = message_field 
        recipient_list = player_emails
        recipient_list.append(current_event.host.email)
        try:
            send_mail(subject, message,  'pickuphockey1@gmail.com', recipient_list, html_message=message_field)

            if len(recipient_list) == 1:
                confirm_message = str(len(recipient_list)) + ' Email Sent'
            else:
                confirm_message = str(len(recipient_list)) + ' Emails Sent'
            messages.success(request, confirm_message )
        except:
            messages.error(request, "Error sending email")
        
        current_event.auto_rosters_sent = True
        current_event.save()
        return redirect(reverse('OrgDash:event_detail' ,args=[current_event.pk]))
    else:
        return render(request, 'OrgDash/Skates/finalize_rosters.html', context)

@login_required
def EmailGuests(request, pk):
    active_event = Skate.objects.get(pk=pk)

    guest_emails = []
    for guest in active_event.player_guests.all():
        guest_emails.append(guest.email)
    for guest in active_event.goalie_guests.all():
        guest_emails.append(guest.email)

OrgDash/templates/OrgDash/Players/create_goalie.html
{% extends 'base.html' %} 
{% block body_block %}
{% load django_bootstrap5 %} 

<div class="container">
    <div class="col-md-6 create-form">
        <h2>Create Goalie</h1>
        <form method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <div class="p-2">
            <input class="btn btn-success" type="submit" value="Create">
        </div>
        </form>
        <div class="p-2">
        <input type=button class="btn btn-danger" value="Cancel" onClick="javascript:history.go(-1);">
        </div>
    </div>
</div>
{% endblock %} 

OrgDash/templates/OrgDash/Players/create_player.html
{% extends 'base.html' %} 
{% block body_block %}
{% load django_bootstrap5 %} 

<div class="container">
    <div class="col-md-6 create-form">
        <h2>Create Player</h1>
        <form method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <div class="p-2">
            <button class="w-100 btn btn-lg btn-green" type="submit">Create</button>
            
        </div>
        </form>
        <div class="p-2">
            <button class="w-100 btn btn-lg btn-gold" type="submit" onClick="javascript:history.go(-1);">Cancel</button>
        
        </div>
    </div>
</div>
{% endblock %} 

OrgDash/templates/OrgDash/Players/player_dash.html
{% extends 'base.html' %} 
{% block body_block %}
{% load static %} 

<div class="container">

  
  
  <div class="d-flex">
    <div class="container-fluid py-3 ">
      <div class="px-4 py-5 my-5 text-center">
        
        <h1 class="display-5 fw-bold text-body-emphasis">Player Dashboard</h1>
        <div class="col-lg-6 mx-auto">
          <p class="lead mb-4">Create and manage players to invite them to your events.</p>
        </div>
        
  {% if messages %}
  <br>
  <div class="p-2" role="alert" id="player-create-sucess"></div>
  <br>
  {% endif %}
      </div>
      <hr>
      <div class="row row-cols-1 row-cols-lg-3 align-items-stretch g-4 py-5">
        <div class="col">
         <a data-bs-toggle="offcanvas" data-bs-target="#myplayers" aria-controls="offcanvasExample"><div class="card card-cover h-100 overflow-hidden text-bg-dark rounded-4 shadow-lg tile-lg" style="background-image: url('{% static 'photos/forest-green.jpg' %}'); background-size: cover;
          background-repeat: no-repeat;">
            <div class="d-flex flex-column h-100 p-5 pb-3 text-white text-shadow-1">
              <h3 class="text-center py-5 display-6 lh-1 fw-bold">My Players</h3>
              <p class="text-center">Click to Manage Players</p>
              
            </div>
          </div>
          </a>
        </div>
  
        <div class="col">
          <a data-bs-toggle="offcanvas" data-bs-target="#mygoalies" aria-controls="offcanvasExample"><div class="card card-cover h-100 overflow-hidden text-bg-dark rounded-4 shadow-lg tile-lg" style="background-image: url('{% static 'photos/blue-fabric.webp' %}'); background-size: cover;
          background-repeat: no-repeat;">
            <div class="d-flex flex-column h-100 p-5 pb-3 text-white text-shadow-1">
              <h3 class="text-center py-5 display-6 lh-1 fw-bold">My Goalies</h3>
              <p class="text-center">Click to Manage Goalies</p>
            
            </div>
          </div>
          </a>
        </div>
        
  
        <div class="col">
          <a data-bs-toggle="offcanvas" data-bs-target="#mygroups" aria-controls="offcanvasExample"><div class="card card-cover h-100 overflow-hidden text-bg-dark rounded-4 shadow-lg tile-lg" style="background-image: url('{% static 'photos/linen-canvas-texture_1373-423.avif' %}'); background-size: cover;
          background-repeat: no-repeat;">
            <div class="d-flex flex-column h-100 p-5 pb-3 text-white text-shadow-1">
              <h3 class="text-center py-5 display-6 lh-1 fw-bold text-dark">My Player Groups</h3>
              <p class="text-center text-dark">Click to Manage Player Groups</p>
           
            </div>
          </div>
        </a>
        </div>
      </div>
     <hr>
    </div>
    
 


  </div>



  
 
 

</div>
  
  <div class="offcanvas offcanvas-start" tabindex="-1" id="mygroups" aria-labelledby="offcanvasExampleLabel">
    <div class="offcanvas-header">
      <h3 class="offcanvas-title" id="offcanvasExampleLabel"><strong>My Player Groups</strong> <a href="" data-bs-toggle="tooltip" data-bs-placement="right" data-bs-title="If you usually invite the same group of players to your events, invite them all at once with a group. Groups are required for recurring events"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-info-circle" viewBox="0 0 16 16">
        <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
        <path d="m8.93 6.588-2.29.287-.082.38.45.083c.294.07.352.176.288.469l-.738 3.468c-.194.897.105 1.319.808 1.319.545 0 1.178-.252 1.465-.598l.088-.416c-.2.176-.492.246-.686.246-.275 0-.375-.193-.304-.533L8.93 6.588zM9 4.5a1 1 0 1 1-2 0 1 1 0 0 1 2 0z"/>
      </svg></a></h3>
      <hr>
      <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
    </div>
    <div class="offcanvas-body">
      <div class="row py-1">
        <a type="button" class="btn btn-gold p-2" href="{% url 'OrgDash:create_player_group' %}">Create Player Group</a>
      </div>
      
      <div class="justify-content-right">
        <div class="table-header">
          
        </div>
        {% if my_groups %} 
        <table class="table table-hover table">
            <thead>
              <tr>
                <th scope="col">Group Name</th>
                
                <th scope="col"></th>
              </tr>
            </thead>
            <tbody>
              {% for group in my_groups %}
              <tr>
                
                <td>{{group.name}}</td>
                <td><a type="button" class="btn btn-gold" href="{% url 'OrgDash:player_group_update' pk=group.pk %}">Manage</a></td>
                {% endfor %}  
              </tr>
            </tbody>
          </table>
        {% else %} 
        <div class="text-center">
          <h3>No player groups created yet</h3>
         </div>
        {% endif %} 
  
      </div>
    </div>
  </div>



  <div class="offcanvas offcanvas-start" tabindex="-1" id="mygoalies" aria-labelledby="offcanvasExampleLabel">
    <div class="offcanvas-header">
      <h2 class="offcanvas-title" id="offcanvasExampleLabel"><strong>My Goalies</strong></h2>
      <hr>
      <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
    </div>
    <div class="offcanvas-body">
      <div class="row py-1">
        <a type="button" class="btn btn-blue p-2" href="{% url 'OrgDash:create_player' %}">Create Goalie</a>
      </div>
      
       <div class="">
      {% if my_goalies %}
      <table class="table table-hover table">
          <thead>
            <tr>
              <th scope="col">Name</th>
              <th scope="col">Skill <a href="" data-bs-toggle="tooltip" data-bs-placement="right" data-bs-title="Player skill is used to make even teams. Rate your players on a scale from 1-10 as accurately as possible."><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-info-circle" viewBox="0 0 16 16">
                <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                <path d="m8.93 6.588-2.29.287-.082.38.45.083c.294.07.352.176.288.469l-.738 3.468c-.194.897.105 1.319.808 1.319.545 0 1.178-.252 1.465-.598l.088-.416c-.2.176-.492.246-.686.246-.275 0-.375-.193-.304-.533L8.93 6.588zM9 4.5a1 1 0 1 1-2 0 1 1 0 0 1 2 0z"/>
              </svg></a>
                </th>
              <th scope="col"></th>
            </tr>
          </thead>
          <tbody>
            {% for player in my_goalies %}
            <tr>
              
              <td>{{player.first_name}} {{player.last_name}}</td>
              <td>{{player.skill}}</td>
              <td><a type="button" class="btn btn-gold" href="{% url 'OrgDash:update_player' player.pk %}">Manage</a></td>
              {% endfor %}  
            </tr>
          </tbody>
        </table>
        {% else %} 
        <div class="text-center">
          <h3>No goalies created yet</h3>
         </div>
      {% endif %} 


    </div>
    </div>
  </div>

  <div class="offcanvas offcanvas-start" tabindex="-1" id="myplayers" aria-labelledby="offcanvasExampleLabel">
    <div class="offcanvas-header">
      <h2 class="offcanvas-title" id="offcanvasExampleLabel"><strong> My Players</strong></h2>
      <hr>
      <button type="button" class="btn-close" data-bs-dismiss="offcanvas" aria-label="Close"></button>
    </div>
    <div class="offcanvas-body">
      <div class="row py-1">
        <a type="button" class="btn btn-green p-2" href="{% url 'OrgDash:create_player' %}">Create Player</a>
      </div>
      <div class="row py-1">
        <a type="button" class="btn btn-blue p-2" href="{% url 'OrgDash:upload_sheet' %}">Create Players from Spreadsheet</a>
      </div>
      <div class="d-flex">
        <div class="py-2 ">
          {% if my_players %} 
          <table class="table table-hover table">
              <thead>
                <tr>
                  <th scope="col">Name</th>
                  <th scope="col">Skill <a href="" data-bs-toggle="tooltip" data-bs-placement="right" data-bs-title="Player skill is used to make even teams. Rate your players on a scale from 1-10 as accurately as possible."><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-info-circle" viewBox="0 0 16 16">
                    <path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/>
                    <path d="m8.93 6.588-2.29.287-.082.38.45.083c.294.07.352.176.288.469l-.738 3.468c-.194.897.105 1.319.808 1.319.545 0 1.178-.252 1.465-.598l.088-.416c-.2.176-.492.246-.686.246-.275 0-.375-.193-.304-.533L8.93 6.588zM9 4.5a1 1 0 1 1-2 0 1 1 0 0 1 2 0z"/>
                  </svg></a>
                    </th>
                  <th scope="col"></th>
                </tr>
              </thead>
              <tbody>
                {% for player in my_players %}
                <tr>
                  
                  <td>{{player.first_name}} {{player.last_name}}</td>
                  <td>{{player.skill}}</td>
                  <td><a type="button" class="btn btn-gold" href="{% url 'OrgDash:update_player' player.pk %}">Manage</a></td>
                  
                  {% endfor %}  
                </tr>
              </tbody>
            </table>
           {% else %}
           <div class="text-center">
            <h3>No players created yet</h3>
           </div>

          {% endif %} 
    
    
        </div>
        </div>
    </div>
  </div>


  </div>
</div>










 


{% if messages %}

    {% for message in messages %}

    <script>



      const alertPlaceholder = document.getElementById('player-create-sucess')
        
        const alert = (message, type) => {
        const wrapper = document.createElement('div')
        wrapper.innerHTML = [
          `<div class="alert alert-success alert-dismissible" role="alert">`,
          `   <div>${message}</div>`,
          '   <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>',
          '</div>'
        ].join('')
        
        alertPlaceholder.append(wrapper)
        }
        
        $(document).ready(function() {
          alert('{{message}}')
        });
      
        </script>
    {% endfor %}

{% endif %}

<script>
  const tooltipTriggerList = document.querySelectorAll('[data-bs-toggle="tooltip"]')
const tooltipList = [...tooltipTriggerList].map(tooltipTriggerEl => new bootstrap.Tooltip(tooltipTriggerEl))
</script>
{% endblock %} 

OrgDash/templates/OrgDash/Players/update_player.html
{% extends 'base.html' %} 
{% block body_block %}
{% load django_bootstrap5 %}

<div class="container">
    <div class="col-md-6 create-form">
        <h2>Edit {{object}}</h2>
        <form method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <div class="p-2">
            <button class="w-100 btn btn-lg btn-green" type="submit">Update</button>
            
        </div>
        </form>
        <div class="p-2">
            <button class="w-100 btn btn-lg btn-gold" type="submit" onClick="javascript:history.go(-1);">Cancel</button>
        
        </div>
        <div class="p-2">
            <a type="button" class="w-100 btn btn-lg btn-danger" href="{% url 'OrgDash:delete_player' player.pk %}">Delete {{object}}</a>
        </div>
    </div>
   
</div>
{% endblock %} 

OrgDash/templates/OrgDash/Players/upload_sheet.html
{% extends 'base.html' %} 
{% block body_block %}
{% load django_bootstrap5 %}
{% load static %} 

<div class="container">
    <div class="p-5 mb-4 bg-light rounded-3">
        <div class="container-fluid py-5">
          <h1 class="display-5 fw-bold">Create Players From Spreadsheet</h1>
          <h2 class="col-md-8 fs-4 px-3">Upload an excel sheet with your players' information</h2>
          <p class="px-4">For best results, format the sheet like the example below.</p>
          <p class="px-4">Be sure that your players' data begins at row 2</p>
          <img src="{% static 'photos/Sheet_Format.png' %}" class="p-4">
          <form method="post" enctype="multipart/form-data">
            {% csrf_token %} 
            {% bootstrap_form form %}
            <div class="p-2">
              <input class="btn btn-blue" type="submit" value="Upload">
            </div>
        </form>
        <div class="p-2">
            <a href="{% url 'OrgDash:player_dash' %}" class="btn btn-gold">Cancel</a>
        </div>
        
        
        </div>
        
      </div>
 
{% endblock %} 